### ISSUE TITLE
Button delay

### ISSUE THREAD

**Issue by Jacob-M-Smith** [jcothran/JIF_2348_EJ_Strong_Tool_Flutter#1]
buttons have a noticeable delay between when you click on them and when they perform their required function

**Comment by Jacob-M-Smith** [comment]
I think that the way we are using the text controllers is causing the slow down. Just a theory

**Comment by AlexMLindemann** [comment]
Do you have hardware acceleration turned on for the emulator?

**Comment by Jacob-M-Smith** [comment]
I dont think it is an emulator problem. I have tested it on a physical device as well as the emulator. It is definitely faster on my phone but there is still a delay. But no I did not have hardware acceleration on for the emulator
